# Generated by Django 4.2 on 2023-04-15 18:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 18, 57, 10, 876155, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 18, 57, 10, 876166, tzinfo=datetime.timezone.utc))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 18, 57, 10, 876384, tzinfo=datetime.timezone.utc))),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatApp.thread')),
            ],
        ),
    ]
