# Generated by Django 4.2 on 2023-04-15 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_message_created_alter_thread_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 20, 26, 12, 416561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 20, 26, 12, 415859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 15, 20, 26, 12, 415869, tzinfo=datetime.timezone.utc)),
        ),
    ]
