# Generated by Django 4.2 on 2023-04-17 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_alter_message_created_alter_thread_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 17, 11, 1, 8, 870451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatApp.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 17, 11, 1, 8, 869626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 17, 11, 1, 8, 869638, tzinfo=datetime.timezone.utc)),
        ),
    ]
